default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 'mm-dev'

test:
  <<: *default
  database: 'mm-test'

production:
  <<: *default
  database: 'mm-prod'
